import { prisma } from '@/lib/prisma'

const DAY_NAMES = ['SUN', 'MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT'] as const

async function isWeekendOrHoliday(projectId: string, date: Date) {
  const [weekends, holidays] = await Promise.all([
    prisma.projectWeekend.findMany({ where: { projectId } }),
    prisma.holiday.findMany({ where: { projectId } }),
  ])
  const dayName = DAY_NAMES[date.getDay()]
  if (weekends.some(w => w.day === dayName)) return true
  return holidays.some(h => {
    const hd = new Date(h.date)
    if (h.isRecurring) return hd.getMonth() === date.getMonth() && hd.getDate() === date.getDate()
    return hd.toDateString() === date.toDateString()
  })
}

/**
 * Auto-split rule: on a weekday (not a weekend/holiday for the project), if the sum
 * of Standard-type hours logged against one project on one date exceeds the
 * project's standardDayHours, the system caps the Standard entries at that limit and
 * moves the excess into a single system-managed Overtime entry (isAutoGenerated).
 * Call this for every (projectId, date) pair touched by an entry save.
 */
export async function applyOvertimeSplit(timesheetId: string, projectId: string, date: Date) {
  const project = await prisma.project.findUnique({ where: { id: projectId } })
  if (!project) return

  if (await isWeekendOrHoliday(projectId, date)) return // weekend/holiday hours aren't subject to this rule

  const entryTypes = await prisma.entryType.findMany({ where: { projectId } })
  const standardType = entryTypes.find(t => t.systemType === 'STANDARD')
  const overtimeType = entryTypes.find(t => t.systemType === 'OVERTIME')
  if (!standardType || !overtimeType) return

  const dayStart = new Date(date); dayStart.setHours(0, 0, 0, 0)
  const dayEnd = new Date(date); dayEnd.setHours(23, 59, 59, 999)

  const standardEntries = await prisma.timesheetEntry.findMany({
    where: {
      timesheetId, projectId, date: { gte: dayStart, lte: dayEnd },
      isAutoGenerated: false,
      OR: [{ entryTypeId: standardType.id }, { entryTypeId: null }],
    },
    orderBy: { createdAt: 'asc' },
  })

  const total = standardEntries.reduce((sum, e) => sum + e.hours, 0)
  const cap = project.standardDayHours
  const existingOvertime = await prisma.timesheetEntry.findFirst({
    where: { timesheetId, projectId, date: { gte: dayStart, lte: dayEnd }, isAutoGenerated: true },
  })

  if (total <= cap) {
    // No longer over the limit — remove any stale auto-generated overtime entry.
    if (existingOvertime) await prisma.timesheetEntry.delete({ where: { id: existingOvertime.id } })
    // Make sure the standard entries carry the Standard entry type.
    for (const e of standardEntries) {
      if (e.entryTypeId !== standardType.id) {
        await prisma.timesheetEntry.update({ where: { id: e.id }, data: { entryTypeId: standardType.id } })
      }
    }
    return
  }

  // Over the limit: trim standard entries down to `cap`, moving the excess to Overtime.
  let remaining = cap
  for (const e of standardEntries) {
    const capped = Math.min(e.hours, Math.max(remaining, 0))
    remaining -= capped
    await prisma.timesheetEntry.update({
      where: { id: e.id },
      data: { hours: capped, entryTypeId: standardType.id },
    })
  }
  const excess = total - cap

  if (existingOvertime) {
    await prisma.timesheetEntry.update({ where: { id: existingOvertime.id }, data: { hours: excess } })
  } else {
    await prisma.timesheetEntry.create({
      data: {
        timesheetId, projectId, date,
        entryTypeId: overtimeType.id,
        hours: excess,
        description: 'Auto-calculated: hours beyond standard day hours',
        isAutoGenerated: true,
      },
    })
  }
}

/** Re-run the overtime split across every (project, date) group on a timesheet. */
export async function recalcOvertimeForTimesheet(timesheetId: string) {
  const entries = await prisma.timesheetEntry.findMany({ where: { timesheetId } })
  const seen = new Set<string>()
  for (const e of entries) {
    const key = `${e.projectId}__${e.date.toDateString()}`
    if (seen.has(key)) continue
    seen.add(key)
    await applyOvertimeSplit(timesheetId, e.projectId, e.date)
  }
  const fresh = await prisma.timesheetEntry.findMany({ where: { timesheetId } })
  const totalHours = fresh.reduce((sum, e) => sum + e.hours, 0)
  await prisma.timesheet.update({ where: { id: timesheetId }, data: { totalHours } })
}

/**
 * Submission-gap rule: an employee can't submit a week (or day) while an earlier
 * week that has entries is still sitting in Draft. Returns an error message if
 * blocked, or null if the submission may proceed.
 */
export async function checkSubmissionGap(userId: string, weekStart: Date): Promise<string | null> {
  const earlierDraft = await prisma.timesheet.findFirst({
    where: {
      userId,
      weekStart: { lt: weekStart },
      status: 'DRAFT',
      entries: { some: {} },
    },
    orderBy: { weekStart: 'asc' },
  })
  if (earlierDraft) {
    return `You have an earlier week (starting ${earlierDraft.weekStart.toDateString()}) still in Draft. Submit that week before this one.`
  }
  return null
}

/**
 * Minimum-week-hours rule: if the governing project requires a minimum number of
 * week hours, block submission until the week's total reaches it.
 */
export async function checkMinWeekHours(timesheetId: string, projectId: string): Promise<string | null> {
  const [project, timesheet] = await Promise.all([
    prisma.project.findUnique({ where: { id: projectId } }),
    prisma.timesheet.findUnique({ where: { id: timesheetId } }),
  ])
  if (!project || !timesheet) return null
  if (!project.minWeekHoursEnabled || !project.minWeekHours) return null
  if (timesheet.totalHours < project.minWeekHours) {
    return `This project requires at least ${project.minWeekHours} hours per week before you can submit (currently ${timesheet.totalHours}).`
  }
  return null
}
