import { prisma } from '@/lib/prisma'
import { WorkflowType, WorkflowStage } from '@prisma/client'

/**
 * Picks which project (and therefore which project's workflow) governs a timesheet,
 * and which workflow type applies.
 *
 * Simplification: a weekly timesheet's entries can span multiple projects, but the
 * doc's approval workflow is defined per project. Until per-project/per-entry
 * approval splitting is built (flagged for the timesheet-entry-logic section), we
 * route the whole week through the workflow of whichever project has the most hours
 * that week. Workflow type is OVERTIME if any entry that week is against the
 * project's Overtime entry type (including the system's auto-split overtime
 * entries — see src/lib/timesheet-rules.ts), otherwise DEFAULT.
 */
export async function resolveWorkflowForTimesheet(timesheetId: string) {
  const entries = await prisma.timesheetEntry.findMany({
    where: { timesheetId },
    include: { project: { include: { entryTypes: true } } },
  })
  if (entries.length === 0) return null

  const hoursByProject = new Map<string, number>()
  for (const e of entries) hoursByProject.set(e.projectId, (hoursByProject.get(e.projectId) ?? 0) + e.hours)
  const [projectId] = [...hoursByProject.entries()].sort((a, b) => b[1] - a[1])[0]

  const project = entries.find(e => e.projectId === projectId)!.project
  const overtimeType = project.entryTypes.find(t => t.systemType === 'OVERTIME')
  const hasOvertime = overtimeType
    ? entries.some(e => e.projectId === projectId && (e.entryTypeId === overtimeType.id || e.isAutoGenerated))
    : false
  const workflowType: WorkflowType = hasOvertime ? 'OVERTIME' : 'DEFAULT'

  const workflow = await prisma.approvalWorkflow.findUnique({
    where: { projectId_type: { projectId, type: workflowType } },
    include: { stages: { orderBy: { order: 'asc' } } },
  })
  // Fall back to the project's default workflow if a type-specific one isn't configured.
  const resolved =
    workflow ??
    (await prisma.approvalWorkflow.findUnique({
      where: { projectId_type: { projectId, type: 'DEFAULT' } },
      include: { stages: { orderBy: { order: 'asc' } } },
    }))

  return { projectId, workflowType: resolved?.type ?? 'DEFAULT', workflow: resolved }
}

/** Whether `userId` holds `roleId` on `projectId` (per the Role Master / project membership). */
export async function userHasProjectRole(userId: string, projectId: string, roleId: string) {
  const membership = await prisma.projectMembership.findUnique({
    where: { projectId_userId: { projectId, userId } },
    include: { roles: true },
  })
  if (!membership) return false
  return membership.roles.some(r => r.roleId === roleId)
}

/** The stage a timesheet is currently waiting on (undefined once past the last stage). */
/** The stage a timesheet is currently waiting on (undefined once past the last stage). */
export function stageAtOrder(stages: WorkflowStage[], order: number) {
  return stages.find(s => s.order === order)
}

