import { NextRequest, NextResponse } from 'next/server'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth'
import { prisma } from '@/lib/prisma'
import * as XLSX from 'xlsx'
import { format } from 'date-fns'

// Exports the signed-in user's timesheet entries as an .xlsx file — the doc's
// "Export as Excel" action on the My Entries table view.
// Optional query params: from, to (YYYY-MM-DD), projectId, entryTypeId, status.
export async function GET(req: NextRequest) {
  const session = await getServerSession(authOptions)
  if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const { searchParams } = new URL(req.url)
  const from = searchParams.get('from')
  const to = searchParams.get('to')
  const projectId = searchParams.get('projectId')
  const entryTypeId = searchParams.get('entryTypeId')
  const status = searchParams.get('status')

  const entries = await prisma.timesheetEntry.findMany({
    where: {
      timesheet: {
        userId: session.user.id,
        ...(status ? { status: status as never } : {}),
      },
      ...(from || to
        ? { date: { ...(from ? { gte: new Date(from) } : {}), ...(to ? { lte: new Date(to) } : {}) } }
        : {}),
      ...(projectId ? { projectId } : {}),
      ...(entryTypeId ? { entryTypeId } : {}),
    },
    include: {
      project: { select: { name: true, code: true } },
      entryType: { select: { name: true } },
      timesheet: { select: { status: true, weekStart: true } },
    },
    orderBy: { date: 'asc' },
  })

  const rows = entries.map(e => ({
    Date: format(e.date, 'yyyy-MM-dd'),
    Day: format(e.date, 'EEEE'),
    Project: e.project.name,
    'Project Code': e.project.code,
    'Entry Type': e.entryType?.name ?? (e.isAutoGenerated ? 'Overtime (auto)' : '—'),
    Hours: e.hours,
    Billable: e.isBillable ? 'Yes' : 'No',
    Status: e.timesheet.status,
    'Week Of': format(e.timesheet.weekStart, 'yyyy-MM-dd'),
    Notes: e.description ?? '',
  }))

  const worksheet = XLSX.utils.json_to_sheet(rows)
  worksheet['!cols'] = [
    { wch: 12 }, { wch: 11 }, { wch: 20 }, { wch: 12 }, { wch: 18 },
    { wch: 8 }, { wch: 9 }, { wch: 12 }, { wch: 12 }, { wch: 30 },
  ]
  const workbook = XLSX.utils.book_new()
  XLSX.utils.book_append_sheet(workbook, worksheet, 'My Entries')

  const buffer = XLSX.write(workbook, { type: 'buffer', bookType: 'xlsx' })

  return new NextResponse(buffer, {
    status: 200,
    headers: {
      'Content-Type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      'Content-Disposition': `attachment; filename="timesheet-entries-${format(new Date(), 'yyyy-MM-dd')}.xlsx"`,
    },
  })
}
