'use client'
import { useEffect, useState, useMemo } from 'react'
import Link from 'next/link'
import { Header } from '@/components/layout/Header'
import { PageLoader } from '@/components/ui/LoadingSpinner'
import { StatusBadge } from '@/components/ui/StatusBadge'
import { Modal } from '@/components/ui/Modal'
import { cn, formatHours } from '@/lib/utils'
import { format, startOfMonth, addMonths, subMonths } from 'date-fns'
import { Table2, CalendarDays, Download, ChevronLeft, ChevronRight, ArrowLeft } from 'lucide-react'

interface Project { id: string; name: string; code: string; color: string }
interface Entry {
  id: string; date: string; hours: number; description: string | null
  isBillable: boolean; isAutoGenerated: boolean
  project: { id: string; name: string; code: string; color: string }
  entryType: { id: string; name: string } | null
  timesheet: { id: string; status: string; weekStart: string }
}
interface CalendarDay { date: string; hours: number; byType: Record<string, number>; dayType: 'WEEKDAY' | 'WEEKEND' | 'HOLIDAY' }

export default function MyEntriesPage() {
  const [tab, setTab] = useState<'table' | 'calendar'>('table')
  const [projects, setProjects] = useState<Project[]>([])
  const [entries, setEntries] = useState<Entry[]>([])
  const [loading, setLoading] = useState(true)

  const [filterProject, setFilterProject] = useState('')
  const [filterStatus, setFilterStatus] = useState('')
  const [filterFrom, setFilterFrom] = useState('')
  const [filterTo, setFilterTo] = useState('')

  const [month, setMonth] = useState(() => startOfMonth(new Date()))
  const [calendarDays, setCalendarDays] = useState<CalendarDay[]>([])
  const [calendarLoading, setCalendarLoading] = useState(false)
  const [dayModal, setDayModal] = useState<CalendarDay | null>(null)

  useEffect(() => {
    fetch('/api/projects').then(r => r.json()).then(setProjects)
  }, [])

  async function loadEntries() {
    setLoading(true)
    try {
      // The "My Entries" table isn't backed by its own list API — reuse the export
      // route's filtering by fetching JSON entries via the timesheets endpoint per
      // project isn't ideal at scale, so this pulls from a lightweight scan of the
      // signed-in user's timesheets instead.
      const res = await fetch('/api/timesheets')
      const timesheets = await res.json()
      const all: Entry[] = []
      for (const ts of timesheets ?? []) {
        for (const e of ts.entries ?? []) {
          all.push({ ...e, timesheet: { id: ts.id, status: ts.status, weekStart: ts.weekStart } })
        }
      }
      setEntries(all)
    } finally {
      setLoading(false)
    }
  }
  useEffect(() => { loadEntries() }, [])

  async function loadCalendar() {
    setCalendarLoading(true)
    try {
      const res = await fetch(`/api/timesheets/calendar?month=${format(month, 'yyyy-MM')}`)
      const data = await res.json()
      setCalendarDays(data.days ?? [])
    } finally {
      setCalendarLoading(false)
    }
  }
  useEffect(() => { if (tab === 'calendar') loadCalendar() }, [tab, month])

  const filtered = useMemo(() => {
    return entries.filter(e => {
      if (filterProject && e.project.id !== filterProject) return false
      if (filterStatus && e.timesheet.status !== filterStatus) return false
      if (filterFrom && e.date < filterFrom) return false
      if (filterTo && e.date > filterTo) return false
      return true
    }).sort((a, b) => b.date.localeCompare(a.date))
  }, [entries, filterProject, filterStatus, filterFrom, filterTo])

  function exportUrl() {
    const params = new URLSearchParams()
    if (filterProject) params.set('projectId', filterProject)
    if (filterStatus) params.set('status', filterStatus)
    if (filterFrom) params.set('from', filterFrom)
    if (filterTo) params.set('to', filterTo)
    return `/api/timesheets/export?${params.toString()}`
  }

  if (loading) return <PageLoader />

  return (
    <>
      <Link href="/timesheets" className="inline-flex items-center gap-1.5 text-sm text-gray-500 hover:text-gray-700 mb-3">
        <ArrowLeft className="w-3.5 h-3.5" /> Back to Timesheets
      </Link>
      <Header
        title="My Entries"
        subtitle="All your logged time, filterable, with table and calendar views"
        actions={
          <a href={exportUrl()} download className="btn-primary text-sm flex items-center gap-1.5">
            <Download className="w-4 h-4" /> Export as Excel
          </a>
        }
      />

      <div className="flex items-center gap-1 p-1 bg-gray-100 dark:bg-gray-800 rounded-xl mb-5 w-fit">
        <button onClick={() => setTab('table')} className={cn('px-4 py-2 rounded-lg text-sm font-semibold', tab === 'table' ? 'bg-white dark:bg-gray-900 shadow-sm text-brand-600' : 'text-gray-500')}>
          <Table2 className="w-3.5 h-3.5 inline mr-1.5 -mt-0.5" /> Table View
        </button>
        <button onClick={() => setTab('calendar')} className={cn('px-4 py-2 rounded-lg text-sm font-semibold', tab === 'calendar' ? 'bg-white dark:bg-gray-900 shadow-sm text-brand-600' : 'text-gray-500')}>
          <CalendarDays className="w-3.5 h-3.5 inline mr-1.5 -mt-0.5" /> Calendar View
        </button>
      </div>

      {tab === 'table' && (
        <>
          <div className="flex flex-wrap gap-3 mb-4">
            <select className="input !w-auto text-sm" value={filterProject} onChange={e => setFilterProject(e.target.value)}>
              <option value="">All projects</option>
              {projects.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}
            </select>
            <select className="input !w-auto text-sm" value={filterStatus} onChange={e => setFilterStatus(e.target.value)}>
              <option value="">All statuses</option>
              {['DRAFT', 'SUBMITTED', 'IN_REVIEW', 'APPROVED', 'REVERTED'].map(s => <option key={s} value={s}>{s}</option>)}
            </select>
            <input type="date" className="input !w-auto text-sm" value={filterFrom} onChange={e => setFilterFrom(e.target.value)} />
            <span className="text-gray-400 text-sm self-center">to</span>
            <input type="date" className="input !w-auto text-sm" value={filterTo} onChange={e => setFilterTo(e.target.value)} />
          </div>

          <div className="card p-0 overflow-hidden overflow-x-auto">
            <table className="w-full text-sm">
              <thead className="bg-gray-50 dark:bg-gray-900/50 text-left text-xs text-gray-400 uppercase tracking-wider">
                <tr>
                  <th className="p-3">Date</th><th className="p-3">Project</th><th className="p-3">Entry Type</th>
                  <th className="p-3">Hours</th><th className="p-3">Status</th><th className="p-3">Notes</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-100 dark:divide-gray-800">
                {filtered.map(e => (
                  <tr key={e.id}>
                    <td className="p-3 text-gray-500 whitespace-nowrap">{format(new Date(e.date), 'MMM d, yyyy')}</td>
                    <td className="p-3">
                      <span className="inline-flex items-center gap-1.5">
                        <span className="w-2 h-2 rounded-full" style={{ background: e.project.color }} />
                        {e.project.name}
                      </span>
                    </td>
                    <td className="p-3 text-gray-500">
                      {e.entryType?.name ?? (e.isAutoGenerated ? 'Overtime (auto)' : '—')}
                    </td>
                    <td className="p-3 font-semibold tabular-nums">{formatHours(e.hours)}</td>
                    <td className="p-3"><StatusBadge status={e.timesheet.status} size="sm" /></td>
                    <td className="p-3 text-gray-400 max-w-xs truncate">{e.description || '—'}</td>
                  </tr>
                ))}
                {!filtered.length && (
                  <tr><td colSpan={6} className="p-6 text-center text-gray-400">No entries match these filters.</td></tr>
                )}
              </tbody>
            </table>
          </div>
        </>
      )}

      {tab === 'calendar' && (
        <div className="card p-5">
          <div className="flex items-center justify-between mb-4">
            <button onClick={() => setMonth(subMonths(month, 1))} className="p-1.5 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-800">
              <ChevronLeft className="w-4 h-4" />
            </button>
            <h3 className="font-bold text-gray-900 dark:text-white">{format(month, 'MMMM yyyy')}</h3>
            <button onClick={() => setMonth(addMonths(month, 1))} className="p-1.5 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-800">
              <ChevronRight className="w-4 h-4" />
            </button>
          </div>

          {calendarLoading ? (
            <div className="h-64 flex items-center justify-center text-gray-400 text-sm">Loading…</div>
          ) : (
            <>
              <div className="grid grid-cols-7 gap-1.5 mb-1.5">
                {['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'].map(d => (
                  <div key={d} className="text-center text-[11px] font-semibold text-gray-400">{d}</div>
                ))}
              </div>
              <div className="grid grid-cols-7 gap-1.5">
                {(() => {
                  const first = calendarDays[0] ? new Date(calendarDays[0].date) : month
                  const leadingBlanks = (first.getDay() + 6) % 7 // Monday-first offset
                  return [
                    ...Array.from({ length: leadingBlanks }, (_, i) => <div key={`b${i}`} />),
                    ...calendarDays.map(day => (
                      <button
                        key={day.date}
                        onClick={() => day.hours > 0 && setDayModal(day)}
                        className={cn(
                          'aspect-square rounded-xl border p-1.5 text-left flex flex-col justify-between transition-colors',
                          day.dayType === 'HOLIDAY' ? 'bg-emerald-50 dark:bg-emerald-950/20 border-emerald-200 dark:border-emerald-900' :
                          day.dayType === 'WEEKEND' ? 'bg-gray-50 dark:bg-gray-900/40 border-gray-200 dark:border-gray-800' :
                          'border-gray-100 dark:border-gray-800 hover:border-brand-300',
                          day.hours > 0 && 'cursor-pointer'
                        )}
                      >
                        <span className="text-[11px] font-semibold text-gray-500">{new Date(day.date).getDate()}</span>
                        {day.hours > 0 && (
                          <span className={cn('text-[11px] font-bold', day.hours < 8 && day.dayType === 'WEEKDAY' ? 'text-amber-600' : 'text-brand-600')}>
                            {formatHours(day.hours)}
                          </span>
                        )}
                      </button>
                    )),
                  ]
                })()}
              </div>
              <div className="flex flex-wrap gap-4 mt-4 text-[11px] text-gray-500">
                <span className="flex items-center gap-1.5"><span className="w-2.5 h-2.5 rounded bg-emerald-100 border border-emerald-300 inline-block" /> Holiday</span>
                <span className="flex items-center gap-1.5"><span className="w-2.5 h-2.5 rounded bg-gray-100 border border-gray-300 inline-block" /> Weekend</span>
                <span className="flex items-center gap-1.5"><span className="w-2.5 h-2.5 rounded bg-amber-100 border border-amber-300 inline-block" /> Below standard hours</span>
              </div>
            </>
          )}
        </div>
      )}

      <Modal open={!!dayModal} onClose={() => setDayModal(null)} title={dayModal ? format(new Date(dayModal.date), 'EEEE, MMMM d') : ''}>
        {dayModal && (
          <div className="space-y-2">
            {Object.entries(dayModal.byType).map(([type, hours]) => (
              <div key={type} className="flex items-center justify-between text-sm">
                <span className="text-gray-600 dark:text-gray-300">{type}</span>
                <span className="font-semibold">{formatHours(hours)}</span>
              </div>
            ))}
            <div className="h-px bg-gray-100 dark:bg-gray-800 my-2" />
            <div className="flex items-center justify-between text-sm font-bold">
              <span>Total</span><span>{formatHours(dayModal.hours)}</span>
            </div>
          </div>
        )}
      </Modal>
    </>
  )
}
